// Code generated by "stringer -type DataUsed"; DO NOT EDIT

package interfaces

import "fmt"

const (
	_DataUsed_name_0 = "BucketStoreNames"
	_DataUsed_name_1 = "RawData"
	_DataUsed_name_2 = "StructuralData"
	_DataUsed_name_3 = "MetaData"
	_DataUsed_name_4 = "LuaScript"
	_DataUsed_name_5 = "AccessStatusData"
	_DataUsed_name_6 = "OwnersData"
	_DataUsed_name_7 = "ContentTypeData"
	_DataUsed_name_8 = "PrimaryNamesData"
	_DataUsed_name_9 = "PrimaryIDsData"
)

var (
	_DataUsed_index_0 = [...]uint8{0, 16}
	_DataUsed_index_1 = [...]uint8{0, 7}
	_DataUsed_index_2 = [...]uint8{0, 14}
	_DataUsed_index_3 = [...]uint8{0, 8}
	_DataUsed_index_4 = [...]uint8{0, 9}
	_DataUsed_index_5 = [...]uint8{0, 16}
	_DataUsed_index_6 = [...]uint8{0, 10}
	_DataUsed_index_7 = [...]uint8{0, 15}
	_DataUsed_index_8 = [...]uint8{0, 16}
	_DataUsed_index_9 = [...]uint8{0, 14}
)

func (i DataUsed) String() string {
	switch {
	case i == 4194304:
		return _DataUsed_name_0
	case i == 8388608:
		return _DataUsed_name_1
	case i == 16777216:
		return _DataUsed_name_2
	case i == 33554432:
		return _DataUsed_name_3
	case i == 67108864:
		return _DataUsed_name_4
	case i == 134217728:
		return _DataUsed_name_5
	case i == 268435456:
		return _DataUsed_name_6
	case i == 536870912:
		return _DataUsed_name_7
	case i == 1073741824:
		return _DataUsed_name_8
	case i == 2147483648:
		return _DataUsed_name_9
	default:
		return fmt.Sprintf("DataUsed(%d)", i)
	}
}
